import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import App from "./_app"; 
import { ThemeProvider } from "@/utils/MaterialUi";

const raleway = Raleway({ subsets: ["latin"], weight: ["300", "400", "500", "700", "100", "200", "600", "800", "900"], });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <ThemeProvider>
        <App>
          {children}
        </App>
        </ThemeProvider>
      </body>
    </html>
  );
}
